// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pharmacy-app/AddMedicineScreen.tsx": () => import("../components/mockups/pharmacy-app/AddMedicineScreen.tsx"),
  "./components/mockups/pharmacy-app/BrowseScreen.tsx": () => import("../components/mockups/pharmacy-app/BrowseScreen.tsx"),
  "./components/mockups/pharmacy-app/CartScreen.tsx": () => import("../components/mockups/pharmacy-app/CartScreen.tsx"),
  "./components/mockups/pharmacy-app/CartScreenAndroid.tsx": () => import("../components/mockups/pharmacy-app/CartScreenAndroid.tsx"),
  "./components/mockups/pharmacy-app/HomeScreen.tsx": () => import("../components/mockups/pharmacy-app/HomeScreen.tsx"),
  "./components/mockups/pharmacy-app/HomeScreenAndroid.tsx": () => import("../components/mockups/pharmacy-app/HomeScreenAndroid.tsx"),
  "./components/mockups/pharmacy-app/LoginScreen.tsx": () => import("../components/mockups/pharmacy-app/LoginScreen.tsx"),
  "./components/mockups/pharmacy-app/PharmacyDashboardScreen.tsx": () => import("../components/mockups/pharmacy-app/PharmacyDashboardScreen.tsx"),
  "./components/mockups/pharmacy-app/PharmacyRegisterScreen.tsx": () => import("../components/mockups/pharmacy-app/PharmacyRegisterScreen.tsx"),
  "./components/mockups/pharmacy-app/ProfileScreen.tsx": () => import("../components/mockups/pharmacy-app/ProfileScreen.tsx")
};
