// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pharmacy-app/BrowseScreen.tsx": () => import("../components/mockups/pharmacy-app/BrowseScreen.tsx"),
  "./components/mockups/pharmacy-app/CartScreen.tsx": () => import("../components/mockups/pharmacy-app/CartScreen.tsx"),
  "./components/mockups/pharmacy-app/HomeScreen.tsx": () => import("../components/mockups/pharmacy-app/HomeScreen.tsx"),
  "./components/mockups/pharmacy-app/ProfileScreen.tsx": () => import("../components/mockups/pharmacy-app/ProfileScreen.tsx")
};
